-- This SQL script is for reference only
-- Spring Boot JPA with hibernate.ddl-auto=update will create the schema automatically

-- Users Table (created by JPA)
-- CREATE TABLE users (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     username VARCHAR(255) UNIQUE NOT NULL,
--     password VARCHAR(255) NOT NULL,
--     email VARCHAR(255) UNIQUE NOT NULL,
--     full_name VARCHAR(255) NOT NULL,
--     phone VARCHAR(255) NOT NULL,
--     address TEXT NOT NULL,
--     role ENUM('ADMIN', 'CUSTOMER', 'EMPLOYEE', 'RIDER') NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

-- Orders Table (created by JPA)
-- CREATE TABLE orders (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     customer_id BIGINT NOT NULL,
--     employee_id BIGINT,
--     rider_id BIGINT,
--     total_amount DECIMAL(10,2) NOT NULL,
--     status ENUM('PLACED', 'ASSIGNED', 'AT_LAUNDRY', 'PROCESSING', 'READY', 'DELIVERED', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PLACED',
--     service_type VARCHAR(255) NOT NULL,
--     item_count INT NOT NULL,
--     address TEXT NOT NULL,
--     progress_note TEXT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     completed_at TIMESTAMP NULL,
--     pickup_date TIMESTAMP NULL,
--     delivery_date TIMESTAMP NULL,
--     FOREIGN KEY (customer_id) REFERENCES users(id),
--     FOREIGN KEY (employee_id) REFERENCES users(id),
--     FOREIGN KEY (rider_id) REFERENCES users(id)
-- );

-- Order Items Table (created by JPA)
-- CREATE TABLE order_items (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     order_id BIGINT NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     service VARCHAR(255) NOT NULL,
--     quantity INT NOT NULL,
--     price DECIMAL(10,2) NOT NULL,
--     FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
-- );

-- Indexes for better performance
-- CREATE INDEX idx_orders_customer_id ON orders(customer_id);
-- CREATE INDEX idx_orders_employee_id ON orders(employee_id);
-- CREATE INDEX idx_orders_rider_id ON orders(rider_id);
-- CREATE INDEX idx_orders_status ON orders(status);
-- CREATE INDEX idx_orders_created_at ON orders(created_at);
-- CREATE INDEX idx_users_username ON users(username);
-- CREATE INDEX idx_users_email ON users(email);
-- CREATE INDEX idx_users_role ON users(role);
